### PR TITLE
#133: on ldap connection error, communicate 504

### LINKED ISSUE #133: LDAP error 401 -> 50x
## Describe the bug
We have witnesses LDAP being unreachable, but the clients got 401 on /token/generate.

This should probably change, we should communicate a different error code (502/504?)

Thanks, @kevinwallimann

### PR DESCRIPTION
**Pull request by dk1844**
This PR introduces different non-ok response to users besides the original 401, on LDAP connection errors.

In this particular situation, failing to connect to LDAP should give users 504.

## Example run with mangled config to induce the error:

`POST http://localhost:9090/token/generate?groups-prefixes=`
with e.g. `Authorization: Basic bXl1c2VybmFtZTp3aGF0LWFyZS15b3UtbG9va2luZy1mb3ItaGVyZT8=`

->
`504`
```
{"error": "LDAP connection failed: LDAP connection issue: corp.bogus.com:636; nested exception is javax.naming.CommunicationException: corp.bogus.com:636 [Root exception is java.net.UnknownHostException: corp.bogus.com]"}
```
@TheLydonKing 

Release notes:
 - For LDAP connection errors, 504 error code is communciated to signify the state difference compared to previsouly present 504

Closes #133

### CODE REVIEW

File: api/src/main/scala/za/co/absa/loginsvc/rest/AuthManagerConfig.scala [hunk 1]
```diff
@@ -36,23 +36,22 @@ import scala.collection.immutable.SortedMap
...
-
-    val authenticationManagerBuilder = http.getSharedObject(classOf[AuthenticationManagerBuilder]).parentAuthenticationManager(null)
+  def authManager(): AuthenticationManager = {
     val configs: Array[ConfigOrdering] = Array(usersConfig, adLDAPConfig).flatten
     val orderedProviders = createAuthProviders(configs)
 
     if(orderedProviders.isEmpty)
       throw ConfigValidationException("No authentication method enabled in config")
 
+    val authenticationManagerBuilder = new AuthenticationManagerBuilder(objectProcessor)
```
Comment (dk1844) [inline api/src/main/scala/za/co/absa/loginsvc/rest/AuthManagerConfig.scala:54]: This change was necessary, otherwise the there was an error that the underlying AuthManager is null.

File: api/src/main/scala/za/co/absa/loginsvc/rest/SecurityConfig.scala [hunk 2]
```diff
@@ -57,29 +63,34 @@ class SecurityConfig @Autowired()(authConfigsProvider: AuthConfigProvider) {
...
         .and()
-      .httpBasic()
-
-    if(ldapConfig != null)
-      {
-        if(ldapConfig.enableKerberos.isDefined)
-        {
-          val kerberos = new KerberosSPNEGOAuthenticationProvider(ldapConfig)
+      // like "httpBasic", but with special handling fo custom exceptions:
+      .addFilterAt(new BasicAuthenticationFilter(authManager, customAuthenticationEntryPoint), classOf[BasicAuthenticationFilter])
```
Comment (dk1844) [inline api/src/main/scala/za/co/absa/loginsvc/rest/SecurityConfig.scala:67]: Without this filter, the entrypoint authentication was was only able to see `InsufficientAuthenticationException`, never any of the custom ones

File: api/src/main/scala/za/co/absa/loginsvc/rest/service/jwt/JWTService.scala [hunk 3]
```diff
@@ -137,7 +138,8 @@ class JWTService @Autowired()(jwtConfigProvider: JwtConfigProvider, authSearchSe
         val prefixedGroups = searchedUser.groups.intersect(userFromOldAccessToken.groups) // only keep groups that were in old token
         User(searchedUser.name, prefixedGroups, searchedUser.optionalAttributes)
       } catch {
-        case _: Throwable => throw new UnsupportedJwtException(s"User ${userFromOldAccessToken.name} not found")
+        case lc: LdapConnectionException => throw lc
+        case _ => throw new UnsupportedJwtException(s"User ${userFromOldAccessToken.name} not found")
```
Comment (dk1844) [inline api/src/main/scala/za/co/absa/loginsvc/rest/service/jwt/JWTService.scala:142]: This can hardly help with the kerberos side of thing, I believe

**Review by dk1844 — COMMENTED** [review]
LGTM
