### PR TITLE
#119 Introduce retries to ad ldap requests

### LINKED ISSUE #119: Introduce retries to AD / LDAP requests
## Background
AD services sometime experience random failures. By introducing retries we can make Login Service slightly more resillient when this occurs.

Reasons of failures observed:
- A Load Balancer AD endpoints can route to nodes that are down for some time, in round robin fashion. Retrying can help with routing to some other nodes.
- LB can be down for a bit (potentially). Retries can help if these failures are short.

## Feature
Introduce retries to AD / LDAP requests

## Example [Optional]
--

## Proposed Solution [Optional]
:warning: Do not retry on errors related to incorrect credentials. Otherwise, this can block the account.

- As a proposal consider a retry with random exponential backoff. If a failure related to server errors (404, 50x) are received, retry after a bit of waiting. The waiting time is determined by the retry number and some random component. 
- The maximum number of retries and the duration between retries should be configurable.

### PR DESCRIPTION
**Pull request by TheLydonKing**
Release Notes:
- Introduced Retry functionality on Ldap requests that are configurable.
- Retries will only occur when it's a connection or Ldap related error. Bad Credentials will cause an immediate failure and will not retry.

closes #119

### CODE REVIEW

**Review by dk1844 — COMMENTED** [review]
Do you know that there are ready-made retry solutions like https://github.com/softwaremill/retry ?

Btw. do you actually test the retry happening? I don't see that in tests

File: api/src/main/scala/za/co/absa/loginsvc/rest/provider/ad/ldap/ActiveDirectoryLDAPAuthenticationProvider.scala [hunk 1]
```diff
@@ -79,6 +73,47 @@ class ActiveDirectoryLDAPAuthenticationProvider(config: ActiveDirectoryLDAPConfi
...
+        case Success(auth) => auth
+        case Failure(ex) if isRetryableException(ex) && n <= attempts =>
+          logger.error(s"AD authentication failed on attempt $n: ${ex.getMessage}. Retrying in ${delayMs * n}ms...")
+          Thread.sleep(delayMs * n)
+          Await.result(attempt(n + 1), Duration.Inf)
+        case Failure(ex: BadCredentialsException) =>
+          logger.error(s"Login of user ${authentication.getName}: ${ex.getMessage}", ex)
+          throw new BadCredentialsException(ex.getMessage)
+        case Failure(ex) =>
+          logger.error(s"Login of user ${authentication.getName}: ${ex.getMessage}", ex)
```
[the remark this answers is not in the document]
Comment (dk1844) [reply api/src/main/scala/za/co/absa/loginsvc/rest/provider/ad/ldap/ActiveDirectoryLDAPAuthenticationProvider.scala:103]: And, if you decide to add tests, such an error could help you determine that the expected number of retries has indeed occurred.

File: api/src/main/scala/za/co/absa/loginsvc/rest/provider/ad/ldap/ActiveDirectoryLDAPAuthenticationProvider.scala [hunk 2]
```diff
@@ -92,15 +85,15 @@ class ActiveDirectoryLDAPAuthenticationProvider(config: ActiveDirectoryLDAPConfi
     def attempt(n: Int): Future[Authentication] = Future {
       Try(baseImplementation.authenticate(authentication)) match {
         case Success(auth) => auth
-        case Failure(ex) if isRetryableException(ex) && n <= attempts =>
```
Comment (dk1844) [inline api/src/main/scala/za/co/absa/loginsvc/rest/provider/ad/ldap/ActiveDirectoryLDAPAuthenticationProvider.scala]: I think this was correct and we should count the retries as extra, so:
- `retryConfig = None`: should be: run once
- `retryConfig = LdapRetryConfig(2, delay)` should be: run once + 2 retries

File: api/src/test/scala/za/co/absa/loginsvc/rest/provider/ad/ldap/ActiveDirectoryLDAPAuthenticationProviderTest.scala [hunk 3]
```diff
@@ -0,0 +1,116 @@
...
+
+    val mockAuthenticationProvider = mock(classOf[AuthenticationProvider])
+    val testActiveDirectoryLDAPAuthenticationProvider =
+      new TestActiveDirectoryLDAPAuthenticationProvider(ldapConfig, mockAuthenticationProvider)
+
+    assertThrows[RuntimeException] {
+      testActiveDirectoryLDAPAuthenticationProvider.authenticate(mockAuthentication)
+    }
+
+    verify(mockAuthenticationProvider, times(2)).authenticate(mockAuthentication)
```
Comment (dk1844) [inline api/src/test/scala/za/co/absa/loginsvc/rest/provider/ad/ldap/ActiveDirectoryLDAPAuthenticationProviderTest.scala:113]:
```suggestion
   verify(mockAuthenticationProvider, times(3)).authenticate(mockAuthentication) // 1 try + 2 retries
```

File: api/src/test/scala/za/co/absa/loginsvc/rest/provider/ad/ldap/ActiveDirectoryLDAPAuthenticationProviderTest.scala [hunk 4]
```diff
@@ -0,0 +1,116 @@
...
+import java.util.Collections
+
+class ActiveDirectoryLDAPAuthenticationProviderTest extends AnyFlatSpec with Matchers {
+
+  private val integratedCfg = LdapUserCredentialsConfig("svc-ldap", "password")
+  private val serviceAccountCfg = ServiceAccountConfig(
+    "CN=%s,OU=Users,OU=Accounts,DC=domain,DC=subdomain,DC=com",
+    Option(integratedCfg),
+    None)
+  private val ldapCfg = ActiveDirectoryLDAPConfig(
```
Comment (dk1844) [inline api/src/test/scala/za/co/absa/loginsvc/rest/provider/ad/ldap/ActiveDirectoryLDAPAuthenticationProviderTest.scala:46]:
```suggestion
  private val ldapCfgNoRetries = ActiveDirectoryLDAPConfig(
```

File: api/src/test/scala/za/co/absa/loginsvc/rest/provider/ad/ldap/ActiveDirectoryLDAPAuthenticationProviderTest.scala [hunk 5]
```diff
@@ -0,0 +1,116 @@
...
+    1,
+    serviceAccountCfg,
+    None,
+    None,
+    None)
+
+  private val principal = CustomUser("user", List("ROLE_USER"), Map("testAtt" -> None))
+  private val mockAuthentication = mock(classOf[Authentication])
+
+  private class TestActiveDirectoryLDAPAuthenticationProvider(config: ActiveDirectoryLDAPConfig, mockAuthenticationProvider: AuthenticationProvider)
```
Comment (dk1844) [inline api/src/test/scala/za/co/absa/loginsvc/rest/provider/ad/ldap/ActiveDirectoryLDAPAuthenticationProviderTest.scala:59]:
```suggestion
  private class TestActiveDirectoryLDAPAuthenticationProviderEventuallySucceeding(config: ActiveDirectoryLDAPConfig, mockAuthenticationProvider: AuthenticationProvider)
```

File: api/src/test/scala/za/co/absa/loginsvc/rest/provider/ad/ldap/ActiveDirectoryLDAPAuthenticationProviderTest.scala [hunk 6]
```diff
@@ -0,0 +1,116 @@
...
+    extends ActiveDirectoryLDAPAuthenticationProvider(config) {
+    private var counter: Int = 1
+    override private[ldap] def createAuthenticationProvider = mockAuthenticationProvider
+    when(mockAuthenticationProvider.authenticate(any[Authentication])).thenAnswer((_: InvocationOnMock) => {
+      val userDetails: UserDetails = UserDetailsWithExtras(
+        new User("user", "password", Collections.singleton(
+          new SimpleGrantedAuthority("ROLE_USER"))), Map("testAtt" -> None))
```
Comment (dk1844) [inline api/src/test/scala/za/co/absa/loginsvc/rest/provider/ad/ldap/ActiveDirectoryLDAPAuthenticationProviderTest.scala:66]:
```suggestion
      val userDetails: UserDetails = UserDetailsWithExtras(
        new User("user", "password", Collections.singleton(new SimpleGrantedAuthority("ROLE_USER"))),
        Map("testAtt" -> None)
      )
```

formatting suggestion

**Review by dk1844 — COMMENTED** [review]
Otherwise LGTM

**Review by dk1844 — APPROVED** [review]
